AWSTemplateFormatVersion: '2010-09-09'
Description: OAuth API Domain

Parameters:
  Doamin:
    Type: String
    Default: alis.to
  SubDomain:
    Type: String
    Default: oauth2
  HostedZoneId:
    Type: String
  RestApiId:
    Type: String
  CertificateArn:
    Type: String

Resources:
  RestApiRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub
      - ${SubDomain}.${Domain}
      - SubDomain: !Ref SubDomain
        Domain: !Ref Doamin
      TTL: 60
      Type: CNAME
      ResourceRecords:
      - !GetAtt RestApiDomain.RegionalDomainName
  RestApiDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !Sub
      - ${SubDomain}.${Domain}
      - SubDomain: !Ref SubDomain
        Domain: !Ref Doamin
      EndpointConfiguration:
        Types:
        - REGIONAL
      RegionalCertificateArn: !Ref CertificateArn
  ApiBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Sub
      - ${SubDomain}.${Domain}
      - SubDomain: !Ref SubDomain
        Domain: !Ref Doamin
      RestApiId: !Ref RestApiId
      Stage: production
    DependsOn:
      - RestApiRecordSet
      - RestApiDomain
