AUTHLETE_OPENID_CONFIGURATION_URL = 'https://api.authlete.com/api/service/configuration'
AUTHLETE_INTROSPECTION_URL = 'https://api.authlete.com/api/auth/introspection/standard'
AUTHLETE_JWK_INFORMATION_URL = 'https://api.authlete.com/api/service/jwks/get'
AUTHLETE_USERINFO_URL = 'https://api.authlete.com/api/auth/userinfo/issue'
AUTHLETE_TOKEN_URL = 'https://api.authlete.com/api/auth/token'

AUTHLETE_INTROSPECTION_SUCCESS_CODE = 'A145001'
AUTHLETE_USERINFO_SUCCESS_CODE = 'A096001'
AUTHLETE_ACCESS_TOKEN_SUCCESS_CODE = 'A050001'
AUTHLETE_REFRESH_TOKEN_SUCCESS_CODE = 'A053001'

AUTHLETE_ERROR_EMPTY_GRANT_TYPE = 'A049302' # grant_typeが空
AUTHLETE_ERROR_INVALID_GRANT_TYPE = 'A049304' # grant_typeが不正な値
AUTHLETE_ERROR_EMPTY_CODE = 'A050302' # codeが空
AUTHLETE_ERROR_INVALID_CODE = 'A050305' # codeが間違ってる
AUTHLETE_ERROR_EXPIRED_CODE = 'A050311' # codeが有効期限切れ
AUTHLETE_ERROR_EMPTY_REDIRECT_URI = 'A050308' # redirect_uriが空
AUTHLETE_ERROR_INVALID_REDIRECT_URI = 'A050309' # redirect_uriが登録された値と違う
AUTHLETE_ERROR_EMPTY_CODE_VERIFIER = 'A050313' # code_verifierが空
AUTHLETE_ERROR_INVALID_CODE_VERIFIER = 'A050315' # code_verifierが違う値
AUTHLETE_ERROR_EMPTY_REFRESH_TOKEN = 'A053302' # refresh_tokenが空
AUTHLETE_ERROR_INVALID_REFRESH_TOKEN = 'A053305' # refresh_tokenが不正
AUTHLETE_ERROR_EMPTY_CLIENT_SECRET = 'A048308' # client_secretが空
AUTHLETE_ERROR_INVALID_CLIENT_SECRET = 'A048311' # client_secretが不正

API_DOMAIN = 'https://oauth2.alis.to'
INTROSPECTION_ENDPOINT = '/introspection'
